/**
    * @description      : 
    * @author           : rrome
    * @group            : 
    * @created          : 17/02/2025 - 06:54:10
    * 
    * MODIFICATION LOG
    * - Version         : 1.0.0
    * - Date            : 17/02/2025
    * - Author          : rrome
    * - Modification    : 
**/
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { ClerkProvider, SignOutButton } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider dynamic>
          <SignOutButton />
          <div className="flex h-screen w-screen items-center justify-center">
            <div className="flex h-1/2 w-1/2 flex-col items-center justify-center">
              <ConvexClientProvider>{children}</ConvexClientProvider>
            </div>
          </div>
          <div className="fixed bottom-0 left-0 right-0 flex h-10 items-center justify-center bg-gray-100">
            <p className="text-sm text-gray-500">
              Powered by{" "}
              <a
                href="https://www.convex.dev"
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-gray-900 underline"
              >
                Convex
              </a>
            </p>
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
